language: r
os: linux
dist: bionic
warnings_are_errors: false
cache: packages

r:
  - oldrel
  - release
  - devel

r_packages:
  - testthat
  - roxygen2

r_github_packages: 
  - thomasp85/patchwork
  - r-spatial/lwgeom

apt_packages:
  - libudunits2-dev
  - libv8-dev
  - libgit2-dev
  - libgdal1-dev
  - libproj-dev
  - libgeos-dev
  - libjq-dev
  - libprotobuf-dev
  - protobuf-compiler

repos: 
  CRAN: https://cran.rstudio.com
  rforge: http://R-Forge.R-project.org

before_install:
  - sudo apt-get update
