language: r

os: linux
dist: xenial

r:
  - oldrel
  - release
  - devel

cache: packages
warnings_are_errors: false

before_install:
  - sudo apt-get update

r_packages:
  - roxygen2
  - testthat

r_github_packages: 
  - thomasp85/patchwork
  - r-spatial/lwgeom

apt_packages:
  - libudunits2-dev
  - libv8-dev
  - libgit2-dev
  - libgdal1-dev
  - libproj-dev
  - libgeos-dev
  - libjq-dev
  - libprotobuf-dev
  - protobuf-compiler
